export const PLANS_LOAD = "PLANS_LOAD";
export const PLANS_LOADED = "PLANS_LOADED";
export const PLANS_ERROR = "PLANS_ERROR";

export const PLANS_CHANGE = "PLANS_CHANGE";
export const PLANS_CHANGED = "PLANS_CHANGED";
export const PLANS_CHANGE_ERROR = "PLANS_CHANGE_ERROR";


export const CHECKOUT_CARD = 'CHECKOUT_CARD';
export const CHECKOUT_CARD_SUCCESS = 'CHECKOUT_CARD_SUCCESS';
export const CHECKOUT_CARD_ERROR = 'CHECKOUT_CARD_ERROR';

export const CANCEL_SUBSCRIPTION = 'CANCEL_SUBSCRIPTION';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_ERROR = 'CANCEL_SUBSCRIPTION_ERROR';

export const CHANGE_SOURCE = 'CHANGE_SOURCE';
export const CHANGE_SOURCE_SUCCESS = 'CHANGE_SOURCE_SUCCESS';
export const CHANGE_SOURCE_ERROR = 'CHANGE_SOURCE_ERROR';
