export const LOGIN_REQUESTING = 'LOGIN_REQUESTING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';

export const ACCOUNT_CONFIRM = 'ACCOUNT_CONFIRM';
export const ACCOUNT_CONFIRMED = 'ACCOUNT_CONFIRMED';

export const ACCOUNT_PASSWORD_RESET = 'ACCOUNT_PASSWORD_RESET';
export const ACCOUNT_PASSWORD_RESET_END = 'ACCOUNT_PASSWORD_RESET_END';

export const ACCOUNT_PASSWORD_UPDATE = 'ACCOUNT_PASSWORD_UPDATE';
export const ACCOUNT_PASSWORD_UPDATED = 'ACCOUNT_PASSWORD_UPDATED';

export const ACCOUNT_UPDATE = 'ACCOUNT_UPDATE';
export const ACCOUNT_UPDATED = 'ACCOUNT_UPDATED';
export const ACCOUNT_ERROR = 'ACCOUNT_ERROR';

export const REFRESH_USER = 'REFRESH_USER';
